package Interfaces;

import Clases.ClDevoluciones;
import Clases.ClGeneradorClaves;
import Clases.ClHoraFecha;
import Clases.ClPrestamos;
import Clases.validarDatos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class JIFrameDevoluciones extends javax.swing.JInternalFrame {

    //Creación de objetos
    ClDevoluciones objDevolucion;
    ClPrestamos objPrestamo;

    private DefaultTableModel modelTablaDetalleDevolucion;

    public JIFrameDevoluciones() {
        initComponents();
        objDevolucion = new ClDevoluciones();
        objPrestamo = new ClPrestamos();
        this.txtCodigoDevolucion.setText(ClGeneradorClaves.GenerarCodigoDevolucion());
    }

    //Funcion para deshabilitarCampos
    public void deshabilitarBotones() {
        txtClaveUsuario.setEditable(false);
        txtNombre.setEditable(false);
        txtCodigoDevolucion.setEditable(false);
        txtFecha.setEditable(false);
        txtAdministrador.setEditable(false);
    }

    //Insercion a la tabla detalleprestamo
    public void EjecutarDevolcion() {
        //Variables
        String isbnx = "";
        int idPrestamo = 0;
        int codigoDev = 0;
        int cantaDevuelta = 0;
        int noFilas = tblDetalleDevolucion.getRowCount();

        //Validamos que los campos contengan los datos necesarios
        if (txtClaveUsuario.getText().equals("") || txtNombre.getText().equals("") || noFilas < 1) {
            JOptionPane.showMessageDialog(this, "Rellene todos los campos,o asegurese de \n realizar una devolucion", "Msj.", JOptionPane.WARNING_MESSAGE);

        } else {
            //Ejecutamos la inserción en la tabla Devolucion
            objDevolucion.realizarDevolucion(txtCodigoDevolucion.getText(), txtFecha.getText(), txtClaveUsuario.getText());

            //Contador para recorrer tantas filas encontradas en la tblDetalleDevolucion
            for (int fila = 0; fila < noFilas; fila++) {
                //Capturamos los valores 
                idPrestamo = Integer.parseInt(tblDetalleDevolucion.getValueAt(fila, 0).toString());
                codigoDev = Integer.parseInt(tblDetalleDevolucion.getValueAt(fila, 1).toString());
                isbnx = tblDetalleDevolucion.getValueAt(fila, 2).toString();
                cantaDevuelta = Integer.parseInt(tblDetalleDevolucion.getValueAt(fila, 4).toString());
                
                //Ejecutamos la inserción en la tabla detalleDevolucion
                objDevolucion.DetalleDevolucion(idPrestamo, codigoDev, isbnx, cantaDevuelta);
                //Ejecutamos estas lineas para actualizar la cantidad prestada
                objDevolucion.ActualizarCantidadPrestada(Integer.parseInt(String.valueOf(tblDetalleDevolucion.getValueAt(fila, 4))), String.valueOf(tblDetalleDevolucion.getValueAt(fila, 2)));
                
                objDevolucion.ActualizarExistenciaMax(cantaDevuelta, isbnx);
            }
            limpiarTabla();
        }
    }

    //funcion para borrar los datos de la tabla tblDetalleDevolucion
    public void limpiarTabla() {
        try{
        int Fila = 0;
        for (int f = 0; f < tblDetalleDevolucion.getColumnCount(); f++) {
            modelTablaDetalleDevolucion.removeRow(Fila);
        }
        }catch(Exception ex){}
    }

    //funcion para borrar los datos de los campos
    public void limpiarCampos() {
        txtClaveUsuario.setText("");
        txtNombre.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel6 = new org.edisoncor.gui.panel.Panel();
        jToolBar1 = new javax.swing.JToolBar();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        panel1 = new org.edisoncor.gui.panel.Panel();
        panel2 = new org.edisoncor.gui.panel.Panel();
        txtClaveUsuario = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        txtNombre = new javax.swing.JTextField();
        panel3 = new org.edisoncor.gui.panel.Panel();
        jLabel1 = new javax.swing.JLabel();
        txtCodigoDevolucion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamosPorUsuarios = new javax.swing.JTable();
        txtFecha = new javax.swing.JTextField();
        panel4 = new org.edisoncor.gui.panel.Panel();
        jLabel2 = new javax.swing.JLabel();
        txtAdministrador = new javax.swing.JTextField();
        panel5 = new org.edisoncor.gui.panel.Panel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDetalleDevolucion = new javax.swing.JTable();

        setClosable(true);
        setMaximizable(true);
        setTitle("Proceso de devolucion");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        panel6.setColorPrimario(new java.awt.Color(50, 116, 53));
        panel6.setColorSecundario(new java.awt.Color(50, 116, 53));

        jToolBar1.setBackground(new java.awt.Color(50, 116, 53));
        jToolBar1.setForeground(new java.awt.Color(50, 116, 53));
        jToolBar1.setRollover(true);

        jButton2.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PkIconos/Img32/imgAgregar.png"))); // NOI18N
        jButton2.setText("Registrar");
        jButton2.setFocusable(false);
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton2);

        jButton3.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PkIconos/Img32/imgCancelar.png"))); // NOI18N
        jButton3.setText("Cancelar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        panel1.setBackground(new java.awt.Color(255, 153, 0));
        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Devoluciones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Vrinda", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panel1.setForeground(new java.awt.Color(255, 255, 255));
        panel1.setColorPrimario(new java.awt.Color(50, 116, 53));
        panel1.setColorSecundario(new java.awt.Color(50, 116, 53));
        panel1.setFont(new java.awt.Font("Vrinda", 0, 12)); // NOI18N

        panel2.setBackground(new java.awt.Color(255, 153, 0));
        panel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Vrinda", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panel2.setColorPrimario(new java.awt.Color(50, 116, 53));
        panel2.setColorSecundario(new java.awt.Color(50, 116, 53));

        txtClaveUsuario.setBackground(new java.awt.Color(58, 145, 64));
        txtClaveUsuario.setFont(new java.awt.Font("Vrinda", 0, 16)); // NOI18N
        txtClaveUsuario.setForeground(new java.awt.Color(255, 255, 255));
        txtClaveUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagen/imgBuscar.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtNombre.setBackground(new java.awt.Color(58, 145, 64));
        txtNombre.setFont(new java.awt.Font("Vrinda", 0, 16)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtClaveUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel2Layout.createSequentialGroup()
                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombre)
                    .addComponent(txtClaveUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        panel3.setBackground(new java.awt.Color(255, 153, 0));
        panel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Proceso General", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Vrinda", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panel3.setColorPrimario(new java.awt.Color(50, 116, 53));
        panel3.setColorSecundario(new java.awt.Color(50, 116, 53));

        jLabel1.setFont(new java.awt.Font("Vrinda", 0, 12)); // NOI18N
        jLabel1.setText("Código Devolución:");

        txtCodigoDevolucion.setBackground(new java.awt.Color(58, 145, 64));
        txtCodigoDevolucion.setFont(new java.awt.Font("Vrinda", 0, 16)); // NOI18N
        txtCodigoDevolucion.setForeground(new java.awt.Color(255, 255, 255));
        txtCodigoDevolucion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Vrinda", 0, 12)); // NOI18N
        jLabel3.setText("Fecha:");

        tblPrestamosPorUsuarios.setBackground(new java.awt.Color(50, 116, 53));
        tblPrestamosPorUsuarios.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        tblPrestamosPorUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblPrestamosPorUsuarios.setGridColor(new java.awt.Color(255, 255, 255));
        tblPrestamosPorUsuarios.setSelectionBackground(new java.awt.Color(58, 145, 64));
        tblPrestamosPorUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPrestamosPorUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPrestamosPorUsuarios);

        txtFecha.setBackground(new java.awt.Color(58, 145, 64));
        txtFecha.setForeground(new java.awt.Color(255, 255, 255));
        txtFecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
        panel3.setLayout(panel3Layout);
        panel3Layout.setHorizontalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 931, Short.MAX_VALUE)
                    .addGroup(panel3Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel3Layout.setVerticalGroup(
            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCodigoDevolucion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtFecha))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addContainerGap())
        );

        panel4.setBackground(new java.awt.Color(255, 153, 0));
        panel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Encargado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Vrinda", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panel4.setColorPrimario(new java.awt.Color(50, 116, 53));
        panel4.setColorSecundario(new java.awt.Color(50, 116, 53));

        jLabel2.setFont(new java.awt.Font("Vrinda", 0, 12)); // NOI18N
        jLabel2.setText("Usuario:");

        txtAdministrador.setBackground(new java.awt.Color(58, 145, 64));
        txtAdministrador.setFont(new java.awt.Font("Vrinda", 0, 16)); // NOI18N
        txtAdministrador.setForeground(new java.awt.Color(255, 255, 255));
        txtAdministrador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout panel4Layout = new javax.swing.GroupLayout(panel4);
        panel4.setLayout(panel4Layout);
        panel4Layout.setHorizontalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel4Layout.setVerticalGroup(
            panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel4Layout.createSequentialGroup()
                .addGroup(panel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel5.setBackground(new java.awt.Color(255, 153, 0));
        panel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle de Devolución", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Vrinda", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        panel5.setColorPrimario(new java.awt.Color(50, 116, 53));
        panel5.setColorSecundario(new java.awt.Color(50, 116, 53));

        tblDetalleDevolucion.setBackground(new java.awt.Color(50, 116, 53));
        tblDetalleDevolucion.setFont(new java.awt.Font("Arial Narrow", 0, 16)); // NOI18N
        tblDetalleDevolucion.setGridColor(new java.awt.Color(255, 255, 255));
        tblDetalleDevolucion.setSelectionBackground(new java.awt.Color(50, 116, 53));
        jScrollPane2.setViewportView(tblDetalleDevolucion);

        javax.swing.GroupLayout panel5Layout = new javax.swing.GroupLayout(panel5);
        panel5.setLayout(panel5Layout);
        panel5Layout.setHorizontalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        panel5Layout.setVerticalGroup(
            panel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                        .addComponent(panel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout panel6Layout = new javax.swing.GroupLayout(panel6);
        panel6.setLayout(panel6Layout);
        panel6Layout.setHorizontalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        panel6Layout.setVerticalGroup(
            panel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel6Layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        JIFrameAlumnos n = new JIFrameAlumnos();
        this.getDesktopPane().add(n);
        n.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tblPrestamosPorUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPrestamosPorUsuariosMouseClicked
        // TODO add your handling code here:
        //Capturamos cada fila de la tabla
        try {
            int fila = this.tblPrestamosPorUsuarios.rowAtPoint(evt.getPoint());

            int cantidadExistente = Integer.parseInt(String.valueOf(this.tblPrestamosPorUsuarios.getValueAt(fila, 4)));
            String CantLibroPrestamos = "";
            int cantidad;

            if (cantidadExistente == 1 || cantidadExistente == 0) {
                int i = JOptionPane.showConfirmDialog(this, "Desea ejecutar la devolución de este ejemplar ?", "Msj.", JOptionPane.YES_NO_OPTION);
                if (i == 0) {

                    modelTablaDetalleDevolucion.addRow(new Object[]{
                        tblPrestamosPorUsuarios.getValueAt(tblPrestamosPorUsuarios.getSelectedRow(), 0),
                        txtCodigoDevolucion.getText(),
                        tblPrestamosPorUsuarios.getValueAt(tblPrestamosPorUsuarios.getSelectedRow(), 2),
                        tblPrestamosPorUsuarios.getValueAt(tblPrestamosPorUsuarios.getSelectedRow(), 3), 1});
                    tblDetalleDevolucion.setModel(modelTablaDetalleDevolucion);
                }
            } else {

                CantLibroPrestamos = JOptionPane.showInputDialog(null, "Introduce la cantidad de ejemplares a devolver:",
                        "Msj.", JOptionPane.INFORMATION_MESSAGE);

                while (CantLibroPrestamos != null && !validarDatos.esEntero(CantLibroPrestamos)) {
                    CantLibroPrestamos = JOptionPane.showInputDialog(null, "Introduce la cantidad de ejemplar a devolver:",
                            "Msj.", JOptionPane.INFORMATION_MESSAGE);
                }
                cantidad = Integer.parseInt(CantLibroPrestamos);

                if (cantidadExistente >= cantidad && cantidad > 0) {
                    modelTablaDetalleDevolucion.addRow(new Object[]{
                        tblPrestamosPorUsuarios.getValueAt(tblPrestamosPorUsuarios.getSelectedRow(), 0),
                        txtCodigoDevolucion.getText(),
                        tblPrestamosPorUsuarios.getValueAt(tblPrestamosPorUsuarios.getSelectedRow(), 2),
                        tblPrestamosPorUsuarios.getValueAt(tblPrestamosPorUsuarios.getSelectedRow(), 3), cantidad});
                    tblDetalleDevolucion.setModel(modelTablaDetalleDevolucion);

                } else {
                    JOptionPane.showMessageDialog(null, "No tiene suficiente ejemplares", "Msj.", JOptionPane.WARNING_MESSAGE);
                }
            }
        } catch (Exception ex) {
            ex.getMessage();
        }
    }//GEN-LAST:event_tblPrestamosPorUsuariosMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        EjecutarDevolcion();
        tblPrestamosPorUsuarios.setModel(objPrestamo.DetallePrestamo(txtNombre.getText()));
        this.txtCodigoDevolucion.setText(ClGeneradorClaves.GenerarCodigoDevolucion());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:

        this.modelTablaDetalleDevolucion = new javax.swing.table.DefaultTableModel(
                null, new String[]{
                    "Cod. Prestamo", "Cod.Devolucion", "ISBN", "Titulo", " Cant. Devuelta "});
        this.txtFecha.setText(ClHoraFecha.FechaFormatoDos());
        deshabilitarBotones();
        txtAdministrador.setText(JPanelLogin.txtUsuario.getText());
    }//GEN-LAST:event_formInternalFrameOpened

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToolBar jToolBar1;
    private org.edisoncor.gui.panel.Panel panel1;
    private org.edisoncor.gui.panel.Panel panel2;
    private org.edisoncor.gui.panel.Panel panel3;
    private org.edisoncor.gui.panel.Panel panel4;
    private org.edisoncor.gui.panel.Panel panel5;
    private org.edisoncor.gui.panel.Panel panel6;
    private javax.swing.JTable tblDetalleDevolucion;
    public static javax.swing.JTable tblPrestamosPorUsuarios;
    private javax.swing.JTextField txtAdministrador;
    public static javax.swing.JTextField txtClaveUsuario;
    private javax.swing.JTextField txtCodigoDevolucion;
    private javax.swing.JTextField txtFecha;
    public static javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
