////package Interfaces;
//import Clases.ClEjemplar;
//
//public class JIFrameConsultaEjemplares extends javax.swing.JInternalFrame {
//    //Objeto de tipo ClEjemplar
//    ClEjemplar objEjemplar;
//    public JIFrameConsultaEjemplares() {
//        initComponents();
//        objEjemplar = new ClEjemplar();
//        this.tblEjemplar.setModel(objEjemplar.ConsultaEjemplar());
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
//    private void initComponents() {
//
//        panelImage1 = new org.edisoncor.gui.panel.PanelImage();
//        panel2 = new org.edisoncor.gui.panel.Panel();
//        jToolBar1 = new javax.swing.JToolBar();
//        jButton1 = new javax.swing.JButton();
//        jButton2 = new javax.swing.JButton();
//        jButton3 = new javax.swing.JButton();
//        jButton4 = new javax.swing.JButton();
//        jButton5 = new javax.swing.JButton();
//        panel1 = new org.edisoncor.gui.panel.Panel();
//        jLabel1 = new javax.swing.JLabel();
//        txtClasificacion = new javax.swing.JTextField();
//        jLabel4 = new javax.swing.JLabel();
//        jLabel5 = new javax.swing.JLabel();
//        jLabel6 = new javax.swing.JLabel();
//        txtIbsn = new javax.swing.JTextField();
//        txtTitulo = new javax.swing.JTextField();
//        txtAutor = new javax.swing.JTextField();
//        jLabel7 = new javax.swing.JLabel();
//        txtEditorial = new javax.swing.JTextField();
//        jLabel8 = new javax.swing.JLabel();
//        jLabel9 = new javax.swing.JLabel();
//        txtCantidad = new javax.swing.JTextField();
//        jScrollPane2 = new javax.swing.JScrollPane();
//        jTextArea1 = new javax.swing.JTextArea();
//        panel3 = new org.edisoncor.gui.panel.Panel();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        tblEjemplar = new javax.swing.JTable();
//        jLabel2 = new javax.swing.JLabel();
//        jTextField2 = new javax.swing.JTextField();
//
//        javax.swing.GroupLayout panelImage1Layout = new javax.swing.GroupLayout(panelImage1);
//        panelImage1.setLayout(panelImage1Layout);
//        panelImage1Layout.setHorizontalGroup(
//            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 100, Short.MAX_VALUE)
//        );
//        panelImage1Layout.setVerticalGroup(
//            panelImage1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGap(0, 100, Short.MAX_VALUE)
//        );
//
//        setBackground(new java.awt.Color(255, 255, 255));
//        setClosable(true);
//        setIconifiable(true);
//        setTitle("Consulta de ejemplares bibliográficos");
//
//        panel2.setColorPrimario(new java.awt.Color(50, 116, 53));
//        panel2.setColorSecundario(new java.awt.Color(50, 116, 53));
//
//        jToolBar1.setBackground(new java.awt.Color(50, 116, 53));
//        jToolBar1.setRollover(true);
//
//        jButton1.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
//        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PkIconos/Img32/imgAgregar.png"))); // NOI18N
//        jButton1.setText("Nuevo");
//        jButton1.setFocusable(false);
//        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
//        jButton1.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//        jToolBar1.add(jButton1);
//
//        jButton2.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
//        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PkIconos/Img32/imgEliminar.png"))); // NOI18N
//        jButton2.setText("Eliminar");
//        jButton2.setFocusable(false);
//        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
//        jButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jToolBar1.add(jButton2);
//
//        jButton3.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
//        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PkIconos/Img32/imgEditar.png"))); // NOI18N
//        jButton3.setText("Actualizar");
//        jButton3.setFocusable(false);
//        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
//        jButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jToolBar1.add(jButton3);
//
//        jButton4.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
//        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PkIconos/Img32/imgCancelar.png"))); // NOI18N
//        jButton4.setText("Cancelar");
//        jButton4.setFocusable(false);
//        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
//        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
//        jToolBar1.add(jButton4);
//
//        jButton5.setFont(new java.awt.Font("Vrinda", 1, 12)); // NOI18N
//        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PkIconos/Img32/imgAceptar.png"))); // NOI18N
//        jButton5.setText("Aceptar");
//        jButton5.setFocusable(false);
//        jButton5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
//        jButton5.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
//        jToolBar1.add(jButton5);
//
//        panel1.setBackground(new java.awt.Color(255, 153, 0));
//        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ejemplares bibliográficos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Vrinda", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
//        panel1.setForeground(new java.awt.Color(255, 255, 255));
//        panel1.setColorPrimario(new java.awt.Color(50, 116, 53));
//        panel1.setColorSecundario(new java.awt.Color(50, 116, 53));
//
//        jLabel1.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
//        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel1.setText("ISBN:");
//
//        txtClasificacion.setBackground(new java.awt.Color(58, 145, 64));
//        txtClasificacion.setFont(new java.awt.Font("Vrinda", 0, 16)); // NOI18N
//        txtClasificacion.setForeground(new java.awt.Color(255, 255, 255));
//        txtClasificacion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
//
//        jLabel4.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
//        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel4.setText("Titulo:");
//
//        jLabel5.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
//        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel5.setText("Clasificación:");
//
//        jLabel6.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
//        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel6.setText("Autor(es)");
//
//        txtIbsn.setBackground(new java.awt.Color(58, 145, 64));
//        txtIbsn.setFont(new java.awt.Font("Vrinda", 0, 16)); // NOI18N
//        txtIbsn.setForeground(new java.awt.Color(255, 255, 255));
//        txtIbsn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
//        txtIbsn.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txtIbsnActionPerformed(evt);
//            }
//        });
//
//        txtTitulo.setBackground(new java.awt.Color(58, 145, 64));
//        txtTitulo.setFont(new java.awt.Font("Vrinda", 0, 16)); // NOI18N
//        txtTitulo.setForeground(new java.awt.Color(255, 255, 255));
//        txtTitulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
//
//        txtAutor.setBackground(new java.awt.Color(58, 145, 64));
//        txtAutor.setFont(new java.awt.Font("Vrinda", 0, 16)); // NOI18N
//        txtAutor.setForeground(new java.awt.Color(255, 255, 255));
//        txtAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
//        txtAutor.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                txtAutorActionPerformed(evt);
//            }
//        });
//
//        jLabel7.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
//        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel7.setText("Editorial:");
//
//        txtEditorial.setBackground(new java.awt.Color(58, 145, 64));
//        txtEditorial.setFont(new java.awt.Font("Vrinda", 0, 16)); // NOI18N
//        txtEditorial.setForeground(new java.awt.Color(255, 255, 255));
//        txtEditorial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
//
//        jLabel8.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
//        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel8.setText("Observación:");
//
//        jLabel9.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
//        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel9.setText("Cantidad :");
//
//        txtCantidad.setBackground(new java.awt.Color(58, 145, 64));
//        txtCantidad.setFont(new java.awt.Font("Vrinda", 0, 16)); // NOI18N
//        txtCantidad.setForeground(new java.awt.Color(255, 255, 255));
//        txtCantidad.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
//
//        jTextArea1.setColumns(20);
//        jTextArea1.setRows(5);
//        jScrollPane2.setViewportView(jTextArea1);
//
//        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
//        panel1.setLayout(panel1Layout);
//        panel1Layout.setHorizontalGroup(
//            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(panel1Layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
//                    .addComponent(jLabel9)
//                    .addComponent(jLabel8)
//                    .addComponent(jLabel7)
//                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addComponent(jLabel5)
//                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
//                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
//                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
//                    .addComponent(txtTitulo, javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(txtAutor)
//                    .addComponent(txtEditorial, javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(txtIbsn, javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(txtClasificacion, javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
//                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        panel1Layout.setVerticalGroup(
//            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(panel1Layout.createSequentialGroup()
//                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel1)
//                    .addComponent(txtIbsn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel5)
//                    .addComponent(txtClasificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel4)
//                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel6)
//                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel7)
//                    .addComponent(txtEditorial, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel9)
//                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jLabel8)
//                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addContainerGap())
//        );
//
//        panel3.setBackground(new java.awt.Color(255, 153, 0));
//        panel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Area de consultas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Vrinda", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
//        panel3.setColorPrimario(new java.awt.Color(50, 116, 53));
//        panel3.setColorSecundario(new java.awt.Color(50, 116, 53));
//
//        tblEjemplar.setBackground(new java.awt.Color(50, 116, 53));
//        tblEjemplar.setModel(new javax.swing.table.DefaultTableModel(
//            new Object [][] {
//                {"ARTURO", "ING EN TI", "10", "ÚNICO"},
//                {"ANA", "TURISMO", "5", "ÚNICO"},
//                {"PEDRO", "TURISMO", "5", "ÚNICO"},
//                {"ALBERTO", "CONTABILIDAD", "7", "ÚNICO"},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null},
//                {null, null, null, null}
//            },
//            new String [] {
//                "Nombres", "Carrera", "Grado", "Grupo"
//            }
//        ) {
//            boolean[] canEdit = new boolean [] {
//                false, false, false, false
//            };
//
//            public boolean isCellEditable(int rowIndex, int columnIndex) {
//                return canEdit [columnIndex];
//            }
//        });
//        tblEjemplar.setGridColor(new java.awt.Color(255, 255, 255));
//        tblEjemplar.setSelectionBackground(new java.awt.Color(58, 145, 64));
//        jScrollPane1.setViewportView(tblEjemplar);
//
//        jLabel2.setFont(new java.awt.Font("Vrinda", 1, 14)); // NOI18N
//        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
//        jLabel2.setText("Buscar por nombres:");
//
//        jTextField2.setBackground(new java.awt.Color(58, 145, 64));
//        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
//        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
//
//        javax.swing.GroupLayout panel3Layout = new javax.swing.GroupLayout(panel3);
//        panel3.setLayout(panel3Layout);
//        panel3Layout.setHorizontalGroup(
//            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(panel3Layout.createSequentialGroup()
//                .addContainerGap()
//                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 983, Short.MAX_VALUE)
//                    .addGroup(panel3Layout.createSequentialGroup()
//                        .addComponent(jLabel2)
//                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
//                        .addGap(0, 0, Short.MAX_VALUE)))
//                .addContainerGap())
//        );
//        panel3Layout.setVerticalGroup(
//            panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel3Layout.createSequentialGroup()
//                .addGap(20, 20, 20)
//                .addGroup(panel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(jLabel2)
//                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addContainerGap())
//        );
//
//        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
//        panel2.setLayout(panel2Layout);
//        panel2Layout.setHorizontalGroup(
//            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(panel2Layout.createSequentialGroup()
//                .addContainerGap()
//                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                .addContainerGap())
//            .addComponent(jToolBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//        panel2Layout.setVerticalGroup(
//            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addGroup(panel2Layout.createSequentialGroup()
//                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
//                .addGap(24, 24, 24)
//                .addGroup(panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
//                    .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                    .addComponent(panel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                .addGap(0, 27, Short.MAX_VALUE))
//        );
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//        );
//        layout.setVerticalGroup(
//            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//            .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//        );
//
//        pack();
//    }// </editor-fold>//GEN-END:initComponents
//
//    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        // TODO add your handling code here:
//        JIFrameEjemplar objEjemplar= new JIFrameEjemplar();
//        this.getDesktopPane().add(objEjemplar);
//        objEjemplar.setVisible(true);
//         
//    }//GEN-LAST:event_jButton1ActionPerformed
//
//    private void txtIbsnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIbsnActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_txtIbsnActionPerformed
//
//    private void txtAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorActionPerformed
//        // TODO add your handling code here:
//    }//GEN-LAST:event_txtAutorActionPerformed
//
//
//    // Variables declaration - do not modify//GEN-BEGIN:variables
//    private javax.swing.JButton jButton1;
//    private javax.swing.JButton jButton2;
//    private javax.swing.JButton jButton3;
//    private javax.swing.JButton jButton4;
//    private javax.swing.JButton jButton5;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JLabel jLabel7;
//    private javax.swing.JLabel jLabel8;
//    private javax.swing.JLabel jLabel9;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JScrollPane jScrollPane2;
//    private javax.swing.JTextArea jTextArea1;
//    private javax.swing.JTextField jTextField2;
//    private javax.swing.JToolBar jToolBar1;
//    private org.edisoncor.gui.panel.Panel panel1;
//    private org.edisoncor.gui.panel.Panel panel2;
//    private org.edisoncor.gui.panel.Panel panel3;
//    private org.edisoncor.gui.panel.PanelImage panelImage1;
//    private javax.swing.JTable tblEjemplar;
//    private javax.swing.JTextField txtAutor;
//    private javax.swing.JTextField txtCantidad;
//    private javax.swing.JTextField txtClasificacion;
//    private javax.swing.JTextField txtEditorial;
//    private javax.swing.JTextField txtIbsn;
//    private javax.swing.JTextField txtTitulo;
//    // End of variables declaration//GEN-END:variables
//}
